server:
  port: 80

# 指定服务名称
spring:
  application:
    name: consumer-order

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址 集群,列表前面的地址宕机会把服务注册到后面的地址
      defaultZone: http://eureka1.com:7002/eureka/,http://eureka2.com:7003/eureka/
