
server:
  port: 7003

spring:
  application:
    name: eureka-server-replica2

eureka:
  instance:
    hostname: eureka2.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      # 两个eureka服务端互相注册，形成集群
      defaultZone: http://eureka1:7002/eureka/
