server:
  port: 7002

spring:
  application:
    name: eureka-server-replica1

eureka:
  instance:
    hostname: eureka1.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      # 两个eureka服务端互相注册，形成集群
      defaultZone: http://eureka2.com:7003/eureka/
