server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trcloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  # resources/mapper/ 里面的所有xml
  mapper-locations: classpath:mapper/*.xml
  # entity别名类 包路径
  type-aliases-package: com.thinrain.cloud.entites

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址 集群,列表前面的地址宕机会把服务注册到后面的地址
      defaultZone: http://eureka1.com:7002/eureka/,http://eureka2.com:7003/eureka/